export const GET_MESSAGE_START = 'GET_MESSAGE_START';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR';
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const CHAT_FINISHED = 'CHAT_FINISHED';

