export const GET_MESSAGE_START = 'GET_QUESTIONS_START';
export const GET_QUESTION_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTION_ERROR = 'GET_QUESTIONS_ERROR';
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const CHAT_FINISHED = 'CHAT_FINISHED';

